version: '3.8'
services:
  zync:
    build: .
    ports:
      - "3000:3000"
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_WS_URL=ws://localhost:8080
    volumes:
      - ./uploads:/usr/src/app/uploads
    restart: unless-stopped